version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./../../../.env
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/mongo-init.js


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./../../../.env


