version: '3.7'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./../../../.env
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    env_file:
      - ./../../../.env

  influxdb:
    image: influxdb:latest
    restart: always
    env_file:
      - influxdb.env
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUX_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - INFLUXDB_DB=nodes
      - INFLUXDB_USER=${INFLUX_USER}
      - INFLUXDB_PASSWORD=${INFLUX_PASSWORD}

  grafana:
    image: grafana/grafana:7.3.5
    ports:
      - 3000:3000
    user: "104"
